# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kishore_signup_page(gui).ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import json
from PyQt5 import QtCore, QtGui, QtWidgets
import os
class Signup_Ui_Dialog(object):

    def openFillForm(self):
        username = self.username.text()
        password = self.password.text()
        confirmpassword = self.confirmpassword.text()

        if len(username)==0 or len(password)==0 or len(confirmpassword)==0:
            self.error1.setText("Please Fill in all the inputs")

        elif password != confirmpassword:
            self.error1.setText("Password did not matched")

        else:
            with open('login.json', "r+") as file:
                data = json.load(file)
                list1 = data['user_login']
                for users in data['user_login']:
                    if users['username'] == username:
                        self.error1.setText("User name is already exists")
                        break
                else:
                    list1.extend([{'username':username,'password':password}])
                    data['user_login'] = list1
                    file.seek(0)
                    json.dump(data, file)

                    MainWindow.close()
                    os.system('python fillinpg.py')

    def redirect_to_home_pg(self):
        MainWindow.close()
        os.system('python welcome.py')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 805)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(0, 0, 1101, 841))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(430, 110, 131, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(330, 200, 351, 51))
        self.label_3.setObjectName("label_3")
        self.username = QtWidgets.QLineEdit(MainWindow)
        self.username.setGeometry(QtCore.QRect(370, 300, 271, 51))
        self.username.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(MainWindow)
        self.password.setGeometry(QtCore.QRect(370, 410, 271, 51))
        self.password.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.confirmpassword = QtWidgets.QLineEdit(MainWindow)
        self.confirmpassword.setGeometry(QtCore.QRect(370, 510, 271, 51))
        self.confirmpassword.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.confirmpassword.setText("")
        self.confirmpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpassword.setObjectName("confirmpassword")
        self.signup = QtWidgets.QPushButton(MainWindow)
        self.signup.setGeometry(QtCore.QRect(410, 610, 181, 41))
        self.signup.setStyleSheet("color: black;\n"
"background-color: rgb(190, 159, 35);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px ;\n"
"")
        self.signup.setObjectName("signup")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(370, 270, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(370, 380, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setGeometry(QtCore.QRect(360, 480, 141, 21))
        self.label_6.setObjectName("label_6")
        self.error1 = QtWidgets.QLabel(MainWindow)
        self.error1.setGeometry(QtCore.QRect(380, 570, 261, 31))
        self.error1.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.error1.setText("")
        self.error1.setObjectName("error1")
        self.home2 = QtWidgets.QPushButton(MainWindow)
        self.home2.setGeometry(QtCore.QRect(410, 690, 181, 41))
        self.home2.setStyleSheet("color: black;\n"
"background-color: rgb(190, 159, 35);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px ;\n"
"")
        self.home2.setObjectName("home2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Signup</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Register a new account</span></p></body></html>"))
        self.signup.setText(_translate("MainWindow", "Sign Up"))
        self.signup.clicked.connect(self.openFillForm)
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#ffffff;\">User Name</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#ffffff;\">Confirm Password</span></p></body></html>"))
        self.home2.setText(_translate("MainWindow", "Home"))
        self.home2.clicked.connect(self.redirect_to_home_pg)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Signup_Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
