# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kishore_Welcome(Gui).ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QDialog, QApplication, QWidget, QStackedWidget


class Welcome_Ui_Dialog():


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1120, 857)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, -10, 1121, 861))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(400, 180, 281, 81))
        self.label_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(390, 280, 331, 41))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(470, 380, 181, 41))
        self.pushButton.setStyleSheet("color:black;\n"
"background-color: rgb(190, 159, 35);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px ;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 470, 251, 51))
        self.pushButton_2.setStyleSheet("color: black;\n"
"background-color: rgb(190, 159, 35);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px ;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">WELCOME</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Sign in or create a new account"))
        self.pushButton.setText(_translate("Dialog", "Login"))

        self.pushButton_2.setText(_translate("Dialog", "Creat a new account"))
        self.pushButton.clicked.connect(self.openLoginPg)
        self.pushButton_2.clicked.connect(self.openSignupPg)
        #widget.setCurrentIndex(widget.currentIndex() + 1)

    def openLoginPg(self):
        Dialog.close()
        os.system('python loginpg.py')
        #self.Dialog = QtWidgets.QDialog()
        #self.ui = Login_Ui_Dialog()
        #self.ui.setupUi(self.Dialog)
        #Dialog.hide()
        #self.Dialog.show()

    def openSignupPg(self):
        Dialog.close()
        os.system('python signpg.py')
        #self.Dialog = QtWidgets.QDialog()
        #self.ui = Signup_Ui_Dialog()
        #self.ui.setupUi(self.Dialog)
        #Dialog.hide()
        #self.Dialog.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    widget = QStackedWidget()
    ui = Welcome_Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
